"use strict";
exports.__esModule = true;
exports.TOOLBAR_INIT__REQUEST = 'TOOLBAR_INIT__REQUEST';
exports.TOOLBAR_INIT = 'TOOLBAR_INIT';
exports.TOOLBAR_LOCALE_CHANGE = 'TOOLBAR_LOCALE_CHANGE';
exports.TOOLBAR_OBJECT_TYPE_CHANGE = 'TOOLBAR_OBJECT_TYPE_CHANGE';
exports.TOOLBAR_FILTER_CHANGE = 'TOOLBAR_FILTER_CHANGE';
exports.TOOLBAR_UPDATED = 'TOOLBAR_UPDATED';
exports.initToolBarRequest = function () { return ({ type: exports.TOOLBAR_INIT__REQUEST }); };
exports.initToolBar = function (toolBarState) { return ({ type: exports.TOOLBAR_INIT, payload: toolBarState }); };
exports.changeLocale = function (locale) { return ({ type: exports.TOOLBAR_LOCALE_CHANGE, payload: locale }); };
exports.changeObjectType = function (objectType) { return ({ type: exports.TOOLBAR_OBJECT_TYPE_CHANGE, payload: objectType }); };
exports.changeFilter = function (filter) { return ({ type: exports.TOOLBAR_FILTER_CHANGE, payload: filter }); };
